version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ritech2024
      MYSQL_DATABASE: event_registration
      MYSQL_USER: event_admin
      MYSQL_PASSWORD: ritech2024
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./server/sqldump:/docker-entrypoint-initdb.d
    networks:
      - my-network

networks:
  my-network: